// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCssnjRdGqETgIRT13ozCYkgzsOjZ_zQYo',
    appId: '1:278670024754:web:cc0a6687c33014ae5c5c2b',
    messagingSenderId: '278670024754',
    projectId: 'stagemate-dd40a',
    authDomain: 'stagemate-dd40a.firebaseapp.com',
    storageBucket: 'stagemate-dd40a.firebasestorage.app',
    measurementId: 'G-J4FJZ59FC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4jRzKobIHlOBUEqUllSCHaqJEaZx7FLA',
    appId: '1:278670024754:android:de33c237cbf5b8cc5c5c2b',
    messagingSenderId: '278670024754',
    projectId: 'stagemate-dd40a',
    storageBucket: 'stagemate-dd40a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA6x451v2kK4cfOZDLVuU5W_tu_YWfCpU',
    appId: '1:278670024754:ios:1d72bdbf5a4cadbc5c5c2b',
    messagingSenderId: '278670024754',
    projectId: 'stagemate-dd40a',
    storageBucket: 'stagemate-dd40a.firebasestorage.app',
    iosBundleId: 'com.netzy.stageMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA6x451v2kK4cfOZDLVuU5W_tu_YWfCpU',
    appId: '1:278670024754:ios:a5be312a827119ca5c5c2b',
    messagingSenderId: '278670024754',
    projectId: 'stagemate-dd40a',
    storageBucket: 'stagemate-dd40a.firebasestorage.app',
    iosBundleId: 'com.example.performanceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCssnjRdGqETgIRT13ozCYkgzsOjZ_zQYo',
    appId: '1:278670024754:web:a2dd50537ad631f45c5c2b',
    messagingSenderId: '278670024754',
    projectId: 'stagemate-dd40a',
    authDomain: 'stagemate-dd40a.firebaseapp.com',
    storageBucket: 'stagemate-dd40a.firebasestorage.app',
    measurementId: 'G-JBD50BCZW2',
  );

}